### ISSUE TITLE
gradlew clean assemble gives: No SLF4J providers were found in 0.7.2 stable

### ISSUE THREAD

**Issue by bwakkie** [kermitt2/grobid#1001]
`./gradlew clean assemble `
gives SLF4J: No SLF4J providers were found in 0.7.2 stable

It could be by system ...
```
openjdk 18.0.2 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+0)
OpenJDK 64-Bit Server VM (build 18.0.2+0, mixed mode)
```
... but I do not know what to do next. Any tip?

```
$ ./gradlew clean assemble                                                                                                                                                     

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jrt:/org.tinylog.api.slf4j/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.

FAILURE: Build failed with an exception.

* What went wrong:
class org.slf4j.helpers.NOPLogger cannot be cast to class org.gradle.api.logging.Logger (org.slf4j.helpers.NOPLogger is in module org.slf4j@2.0.3 of loader 'app'; org.gradle.api.logging.Logger is in unnamed module o
f loader org.gradle.internal.classloader.VisitableURLClassLoader @42d8062c)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.ClassCastException: class org.slf4j.helpers.NOPLogger cannot be cast to class org.gradle.api.logging.Logger (org.slf4j.helpers.NOPLogger is in module org.slf4j@2.0.3 of loader 'app'; org.gradle.api.logging
.Logger is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @42d8062c)
	at org.gradle.api.logging.Logging.getLogger(Logging.java:39)
	at org.gradle.launcher.cli.DebugLoggerWarningAction.<init>(DebugLoggerWarningAction.java:57)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:235)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)



```

**Comment by kermitt2** [comment]
Hi @bwakkie !

Likely JDK too high: `openjdk 18.0.2` for the version of logger implementation. In any case, you currently need a lower version of the JDK to run Grobid, due to the dynamic libraries, see:

https://grobid.readthedocs.io/en/latest/Install-Grobid/#getting-grobid

**Comment by bwakkie** [comment]
Great,
after ...
`export PATH="/usr/lib/jvm/java-8-openjdk/bin/:$PATH"`
... it worked! Well ... it is compiling as we speak.
