### ISSUE TITLE
cant load deep learning model 

### ISSUE THREAD

**Issue by helplessness** [kermitt2/grobid#1064]
```
[Wapiti] Loading model: "/data1/tf_data/pro/project/citation/grobid-master/grobid-home/models/reference-segmenter/model.wapiti"
ERROR [2023-11-28 09:57:51,378] org.grobid.core.jni.JEPThreadPool: JEP initialization failed
! jep.JepException: <class 'ImportError'>: Traceback (most recent call last):
!   File "/home/phoenix/anaconda3/envs/grobid/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
!     from tensorflow.python._pywrap_tensorflow_internal import *
! ImportError: /home/phoenix/anaconda3/envs/grobid/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: PyThread_tss_alloc
!
!
! Failed to load the native TensorFlow runtime.
! See https://www.tensorflow.org/install/errors for some common causes and solutions.
! If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
! at /home/phoenix/anaconda3/envs/grobid/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.<module>(pywrap_tensorflow.py:78)
! at /home/phoenix/anaconda3/envs/grobid/lib/python3.9/site-packages/tensorflow/python/__init__.<module>(__init__.py:36)
! at /home/phoenix/anaconda3/envs/grobid/lib/python3.9/site-packages/tensorflow/__init__.<module>(__init__.py:37)
! at /data1/tf_data/pro/project/citation/delft-master/delft/utilities/Embeddings.<module>(Embeddings.py:17)
! at <string>.<module>(<string>:1)
! at jep.Jep.eval(Native Method)
! at jep.Jep.eval(Jep.java:312)
! at org.grobid.core.jni.JEPThreadPool.initializeJepInstance(JEPThreadPool.java:89)
! at org.grobid.core.jni.JEPThreadPool.createJEPInstance(JEPThreadPool.java:113)
! at org.grobid.core.jni.JEPThreadPool.getJEPInstance(JEPThreadPool.java:151)
! at org.grobid.core.jni.DeLFTModel$InitModel.run(DeLFTModel.java:53)
! at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
! at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
! at java.base/java.lang.Thread.run(Thread.java:829)
Model path: /data1/tf_data/pro/project/citation/grobid-master/grobid-home/models/reference-segmenter/model.wapiti
[Wapiti] Loading model: "/data1/tf_data/pro/project/citation/grobid-master/grobid-home/models/figure/model.wapiti"
Model path: /data1/tf_data/pro/project/citation/grobid-master/grobid-home/models/figure/model.wapiti
[Wapiti] Loading model: "/data1/tf_data/pro/project/citation/grobid-master/grobid-home/models/table/model.wapiti"
Model path: /data1/tf_data/pro/project/citation/grobid-master/grobid-home/models/table/model.wapiti
[Wapiti] Loading model: "/data1/tf_data/pro/project/citation/grobid-master/grobid-home/models/funding-acknowledgement/model.wapiti"
Model path: /data1/tf_data/pro/project/citation/grobid-master/grobid-home/models/funding-acknowledgement/model.wapiti
<===========--> 91% EXECUTING [2m 28s]
```
python : 3.9 

I have received the above error. Anyone know how to solve it？

**Comment by kermitt2** [comment]
Hi @helplessness !

Did you follow the instructions https://grobid.readthedocs.io/en/latest/Deep-Learning-models/ for installing the DL environment?

**Comment by helplessness** [comment]
yes 
I follow it 

> Hi @helplessness !
> 
> Did you follow the instructions https://grobid.readthedocs.io/en/latest/Deep-Learning-models/ for installing the DL environment?

**Comment by helplessness** [comment]
> Hi @helplessness !
> 
> Did you follow the instructions https://grobid.readthedocs.io/en/latest/Deep-Learning-models/ for installing the DL environment?

I wonder if it's a problem with a library version。but I follow it

**Comment by kermitt2** [comment]
Ok then next questions, can you describe your environment: OS, JDK version, Python & CUDA version, which virtualenv? 

Did you use the script under `./grobid-home/scripts/install_jep_lib.sh ` to install JEP ? On my side I am still using JEP `4.0.2` as in the script, and I have not tried with more recent versions.

**Comment by helplessness** [comment]
> Ok then next questions, can you describe your environment: OS, JDK version, Python & CUDA version, which virtualenv?
> 
> Did you use the script under `./grobid-home/scripts/install_jep_lib.sh ` to install JEP ? On my side I am still using JEP `4.0.2` as in the script, and I have not tried with more recent versions.

linux 22.04
jdk 11
python 3.9 with conda
cuda 12.2
and I use grobid-home/scripts/install_jep_lib.sh  to install JEP
 I suspect it's the tensorflow version, but I don't know much about it.

**Comment by helplessness** [comment]
Hi, @kermitt2 ，thank you for your reply. I solved the problem of using deep learning models using Docker. But I think my problem still exists.I want to use deep learning models because I feel that I cannot accurately identify images and attachments. But I think this problem still exists like this picture. Do I have any good ways to solve this problem?

<img width="1079" alt="1701306980158" src="https://github.com/kermitt2/grobid/assets/34809624/8a3c8489-74a6-4e2f-8488-09be2617c89a">

**Comment by lfoppiano** [comment]
You can use the deep learning models using the docker image: `grobid/grobid:....` see: https://grobid.readthedocs.io/en/latest/Grobid-docker/#deep-learning-and-crf-image


You can also tune more in detail what DL model to use by providing your configuration mounted as a volume when you run the container: https://grobid.readthedocs.io/en/latest/Grobid-docker/#configure-using-the-yaml-config-file

**Comment by lfoppiano** [comment]
> But I think my problem still exists.I want to use deep learning models because I feel that I cannot accurately identify images and attachments. But I think this problem still exists like this picture. Do I have any good ways to solve this problem?

@helplessness  going back through this, what is the problem with the image? it seems fine to me.

**Comment by helplessness** [comment]
> > But I think my problem still exists.I want to use deep learning models because I feel that I cannot accurately identify images and attachments. But I think this problem still exists like this picture. Do I have any good ways to solve this problem?
> 
> @helplessness going back through this, what is the problem with the image? it seems fine to me.

@lfoppiano ，Thank you for your reply. The places marked in the image seem to be incorrect. Take fig1 as an example, I want to mark the red area, but the model only marks the blue area.
