### ISSUE TITLE
pdf2xml Fail on specific PDF file

### ISSUE THREAD

**Issue by bhecht2** [kermitt2/grobid#150]
[grobid bad.pdf](https://github.com/kermitt2/grobid/files/625057/grobid.bad.pdf)
Hi,

The attached file causes pdf2xml process to crash the machine.
I see the process is stuck and memory usage starts rising untill getting to 100%.

Thanks

**Comment by kermitt2** [comment]
Hello!

Thanks for reporting the issue. 

On Ubuntu I have a timeout for this file, no crash (in principle the timeout should prevent any crash of the JVM). What is your architecture/environment? 

I need to explore with pdf2xml why we have this problem with this file... I am working on a branch *modified-pdf2xml* where I try to address various issues related to pdf2xml (the modifications of pdf2xml have unfortunately also an impact on the rest of GROBID).

**Comment by bhecht2** [comment]
Hi

Thanks for the quick reply. 

I'm running Cent OS. 

What timeout are you mentioning, the  one in GROBID?
I tested this directly on pdf2xml running it as a command line. No timeout occurred. 

Thanks

**Comment by bhecht2** [comment]
Hi again,

In the grobid.properties i see this configuration:
grobid.3rdparty.pdf2xml.memory.limit.mb=6096

Does this means the pdf2xml process might consume up to 6GB of memory for it to run?
If so, why does it need so much? Does it depend on the size of the file?
What is the minimum possible for it to run?

Thanks a lot

**Comment by kermitt2** [comment]
Yes I was referring to the GROBID's timeout: 

```
[ERROR] org.grobid.core.process.ProcessPdf2Xml: pdftoxml return message: 

[ERROR] org.grobid.service.process.GrobidRestProcessFiles: An unexpected exception occurs. 
org.grobid.core.exceptions.GrobidException: [TIMEOUT] PDF to XML conversion timed out
	at org.grobid.core.document.DocumentSource.processPdf2XmlServerMode(DocumentSource.java:213)
	at org.grobid.core.document.DocumentSource.pdf2xml(DocumentSource.java:125)
...
```

The equivalent  command line is working indeed also for me, but it takes very long time:

```
lopez@smallbook:~/grobid/grobid-service$ time /home/lopez/grobid/grobid-home/pdf2xml/lin-64/pdftoxml -blocks -noImageInline -fullFontName -noImage -annotation /home/lopez/test/grobid.bad.pdf /home/lopez/grobid/grobid-home/tmp/FdGJVHsSAZ.lxml

real	1m38.011s
```
And you're right, this property ```grobid.3rdparty.pdf2xml.memory.limit.mb``` is used to limit the maximum amount of memory used by the external pdf2xml process, in order to protect the JVM from OOM errors. 

pdf2xml does usually not need so much memory, but it could be the case for very large PDF (like a Ph.D. thesis with many figures), and it can go - very rarely above 6GB.

**Comment by lfoppiano** [comment]
I'm closing this as it doesn't seems an open issue. 
@bhecht2 if you have more questions or remarks, feel free to reopen it.

**Comment by kermitt2** [comment]
reopen ;)

**Comment by ShriharshAmbhore** [comment]
Hello @kermitt2 ,
I recently faced similar issue (PDF2XML timeout error) while trying to generate the training data using the 0.5.1 release version of GROBID. I have attached the pdf file for reference.
Can you please suggest suitable steps to be taken.
[22654.pdf](https://github.com/kermitt2/grobid/files/2476827/22654.pdf)

Regards,
Shriharsh Ambhore.

**Comment by kermitt2** [comment]
So right now, there is no runtime issue with `grobid bad.pdf`, processed in 800ms.

The second example `22654.pdf` @shriharsh-a, has no more timeout but it is rejected by Grobid after parsing because it has too many tokens (1,273,782 tokens, but the limit is 1,000,000). The reason is that there are kilometres of text crap in this PDF. If you cut and paste the content with a basic PDF viewer, you will tons of:
 
```
@@@@@@@@@@@@@@@@@@@@@@@(Y
?@@@@@@@@@@@@@@@@@@@@@@(Y?
?@@@@@@@@@@@@@@@@@@@@@0Y
?3@@@@@@@@@@@@@@@@@@(M
?N@@@@@@@@@@@@@@@@@(Y?
3@@@@@@@@@@@@@@@(Y
V'@@@@@@@@@@@@@(Y?
?V'@@@@@@@@@@@0Y
N@@@@@@@@0M?
?3@@@@@0M?
?V4@0M
```

between some lost pieces of normal text. 

Maybe it's a cheap protection by the publisher to avoid accessing the content programmatically. It's not easy, but maybe we could think about some heuristics in pdfalto to manage this.
