### ISSUE TITLE
Error reported by XML parser: Invalid byte 2 of 3-byte UTF-8 sequence.

### ISSUE THREAD

**Issue by moissinac** [kermitt2/grobid#195]
Hello
Thank's for your tool
I'm getting the same error with a lot of pdf files
I'm trying the grobid service 0.4.1 on a windows 10 install
A sample PDF file is available here
http://givingsense.eu/sembib/data/srcPdf/A%20Branch%20and%20Bound%20Method%20for%20the%20Aggregation%20of%20Symmetric%20Relations.pdf
which is accepted by several PDF tools
Here is the begining of the log for a failing pdf
[DEBUG] org.grobid.core.engines.Engine: Ending processing fullTextToTEI on C:\outils\SemanticWeb\grobid-grobid-parent-0.4.1\grobid-home\tmp\origin3628539216410344526.pdf. Time to process: 22525ms
Error on line 46 column 48
  SXXP0003: Error reported by XML parser: Invalid byte 2 of 3-byte UTF-8 sequence.
[ERROR] org.grobid.service.process.GrobidRestProcessFiles: An unexpected exception occurs.
net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 46; columnNumber: 48; Invalid byte 2 of 3-byte UTF-8 sequence.
        at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:418)
        at net.sf.saxon.event.Sender.send(Sender.java:193)
        at net.sf.saxon.event.Sender.send(Sender.java:50)
        at net.sf.saxon.Configuration.buildDocument(Configuration.java:2973)
        at net.sf.saxon.query.StaticQueryContext.buildDocument(StaticQueryContext.java:211)
        at org.grobid.core.utilities.XQueryProcessor.<init>(XQueryProcessor.java:48)
        at org.grobid.core.utilities.BibDataSetContextExtractor.getCitationReferences(BibDataSetContextExtractor.java:56)
        at org.grobid.core.visualization.CitationsVisualizer.getJsonAnnotations(CitationsVisualizer.java:248)
        at org.grobid.service.process.GrobidRestProcessFiles.processPDFReferenceAnnotation(GrobidRestProcessFiles.java:727)
        at org.grobid.service.GrobidRestService.processPDFReferenceAnnotation(GrobidRestService.java:649)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
...

**Comment by kermitt2** [comment]
Hello !

The PDF file is working fine with current master version (0.4.2-SNAPSHOT). The pdf parser has been improved in between (it uses now the following fork: https://github.com/kermitt2/pdf2xml and is more robust). 

You can test it with the latest version via the online demo: http://grobid.science-miner.com

The current master with this new pdf parser is not yet available on Windows, some binaries need to be recompiled for Win64.

**Comment by kermitt2** [comment]
You can however make the master version work on Windows 10 as explained by @UntoterOstgote on issue #185.

**Comment by lfoppiano** [comment]
@moissinac the issue you had with the UTF-8 XML parsing should be now fixed, give it a try and let us know

**Comment by moissinac** [comment]
Tested with success with the online version and the service version for the latest release
Many thank's
