### ISSUE TITLE
Java NullPointerException/InvocationTargetException error for processAuthorsHeader

### ISSUE THREAD

**Issue by dominic-sps** [kermitt2/grobid#197]
I am trying GROBID with one of your grobid-example\src\test\resources\Wang_paperAVE2008.pdf and copied this pdf in \test\in for my following test.

In Windows 7, 64bit with **processHeader**:
`java -Xmx1024m -jar \grobid\grobid-core\target\grobid-core-0.4.2-SNAPSHOT.one-jar.jar -gH \grobid\grobid-home -gP \grobid\grobid-home\config\grobid.properties -dIn \test\in -dOut \test\out -exe processHeader`

Produces some output. Now I am running the same with **processAuthorsHeader**. In the screen I am seeing
```
JarClassLoader: Warning: org/apache/lucene/analysis/cn/smart/hhmm/SegTokenFilter.class in lib/lucene-analyzers-smartcn-4.5.1.jar is hidden by lib/wipo-analysers-0.0.1.jar (with different bytecode)
JarClassLoader: Warning: org/w3c/dom/UserDataHandler.class in lib/xom-1.2.5.jar is hidden by lib/xml-apis-1.4.01.jar (with different bytecode)
[Wapiti] Loading model: "D:\grobid\grobid-home\models\name\header\model.wapiti"
Model path: D:\grobid\grobid-home\models\name\header\model.wapiti
[Wapiti] Loading model: "D:\grobid\grobid-home\models\name\citation\model.wapiti"
Model path: D:\grobid\grobid-home\models\name\citation\model.wapiti
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.grobid.core.utilities.Utilities.launchMethod(Utilities.java:396)
        at org.grobid.core.main.batch.GrobidMain.main(GrobidMain.java:176)
        ... 6 more
Caused by: java.lang.NullPointerException
        at org.grobid.core.engines.ProcessEngine.processAuthorsHeader(ProcessEngine.java:240)
        ... 12 more

```
I am getting similar error for **processAffiliation** as well.

**Comment by kermitt2** [comment]
Hello Dominic,

`-exe processAuthorsHeader` and `-exe ProcessAffiliation` takes a `string` as input (`-s`) not a PDF file. See the documentation: http://grobid.readthedocs.io/en/latest/Grobid-batch/#processauthorsheader

However, when failing as you report, the tool should give an error message explaining what are the expected parameters, and not a NPE.

**Comment by lfoppiano** [comment]
I've changed this with something like
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.grobid.core.utilities.Utilities.launchMethod(Utilities.java:396)
	at org.grobid.core.main.batch.GrobidMain.main(GrobidMain.java:176)
	... 6 more
Caused by: org.grobid.core.exceptions.GrobidResourceException: [GENERAL] Cannot read the input data for processAuthorHeader. Check the documentation. 
	at org.grobid.core.engines.ProcessEngine.processAuthorsHeader(ProcessEngine.java:232)
	... 12 more
```
