### ISSUE TITLE
Compilation Fails in the new code

### ISSUE THREAD

**Issue by dominic-sps** [kermitt2/grobid#227]
grobid-trainer compilation fails in windows.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.grobid.trainer.evaluation.EvaluationUtilitiesTest
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.577 sec <<< FAILURE!
testMetricsReal(org.grobid.trainer.evaluation.EvaluationUtilitiesTest)  Time elapsed: 0.109 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <378>
     but: was <1>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.grobid.trainer.evaluation.EvaluationUtilitiesTest.testMetricsReal(EvaluationUtilitiesTest.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.grobid.trainer.sax.TEICitationSaxParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.062 sec

Results :

Failed tests:   testMetricsReal(org.grobid.trainer.evaluation.EvaluationUtilitiesTest): (..)

Tests run: 8, Failures: 1, Errors: 0, Skipped: 0

```

[org.grobid.trainer.evaluation.EvaluationUtilitiesTest.txt](https://github.com/kermitt2/grobid/files/1259074/org.grobid.trainer.evaluation.EvaluationUtilitiesTest.txt)
[org.grobid.trainer.sax.TEICitationSaxParserTest.txt](https://github.com/kermitt2/grobid/files/1259073/org.grobid.trainer.sax.TEICitationSaxParserTest.txt)
[TEST-org.grobid.trainer.evaluation.EvaluationUtilitiesTest.xml.txt](https://github.com/kermitt2/grobid/files/1259076/TEST-org.grobid.trainer.evaluation.EvaluationUtilitiesTest.xml.txt)
[TEST-org.grobid.trainer.sax.TEICitationSaxParserTest.xml.txt](https://github.com/kermitt2/grobid/files/1259075/TEST-org.grobid.trainer.sax.TEICitationSaxParserTest.xml.txt)

**Comment by kermitt2** [comment]
Thank you @dominic-sps, I think it's a problem with Windows end-of-lines in the resource test file. 
I modify the test in commit 414a609d3a4ccbe574b58c9a8c25684b49afa658, it could work now (but not sure, I don't have a Windows machine).

**Comment by lfoppiano** [comment]
as an addition, the method `FileUtils.readFileToString(String);` [is deprecated](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FileUtils.html#readFileToString(java.io.File)), in favour of `FileUtils.readFileToString(String, Charset);`.

**Comment by kermitt2** [comment]
@lfoppiano also updated now -> c438d3a277529fe04e1a3fe2436ef92822688f52
