### ISSUE TITLE
Build failed with an exception during Installation command

### ISSUE THREAD

**Issue by wooooooooooooooowastaken** [kermitt2/grobid#261]
**1. The installation documentation lists the install command as ./gradlew clean install** and it took me awhile to figure out that the period and slash need to be removed in order to execute the command. I'm certain it's basic knowledge but there may be others like me little to no command line or programming experience who are following the directions literally and may also get stuck there. 

**2. [FAILURE: Build failed with an exception.] after entering the following in the command prompt:**

cd C:\Users\username-redacted\Documents\directoryname-without-spaces\grobid
gradlew clean install
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grobid-core:compileJava'.
> Could not find tools.jar. Please check that C:\Program Files (x86)\Java\jre1.8.0_151 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 58s
6 actionable tasks: 1 executed, 5 up-to-date
```
**gradlew clean install --info**
```
> Task :grobid-core:compileJava
Putting task artifact state for task ':grobid-core:compileJava' into context took 0.0 secs.
Executing task ':grobid-core:compileJava' (up-to-date check took 0.102 secs) due to:
  Task has failed previously.
All input files are considered out-of-date for incremental task ':grobid-core:compileJava'.
Compiling with JDK Java compiler API.

:grobid-core:compileJava (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.129 secs.`
```
**gradlew clean install --stacktrace**
```
`Exception` is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':grobid-core:compileJava'.`
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        ...
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalStateException: Could not find tools.jar. Please check that C:\Program Files (x86)\Java\jre1.8.0_151 contains a valid JDK installation.
        at org.gradle.api.internal.tasks.compile.JdkTools.<init>(JdkTools.java:65)
        at org.gradle.api.internal.tasks.compile.JdkTools.current(JdkTools.java:51)
        ...
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 102 more
```
**gradlew clean install --debug** with lines containing [debug] removed except for a few:
```09:54:37.883 [INFO] [org.gradle.internal.nativeintegration.services.NativeServices] Initialized native services in: C:\Users\[username-redacted]\.gradle\native
09:54:37.925 [DEBUG] [org.gradle.internal.nativeintegration.services.NativeServices] Native-platform posix files integration is not available. Continuing with fallback.
09:54:38.048 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Executing build bcfefbda-3e05-49e6-a354-102021351d94.1 in daemon client {pid=5084}09:54:38.219 [INFO] [org.gradle.launcher.daemon.server.exec.LogToClient] The client will now receive all logging from the daemon (pid: 9024). The daemon log file: C:\Users\[username-redacted]\.gradle\daemon\4.2.1\daemon-9024.out.log
09:54:38.220 [INFO] [org.gradle.launcher.daemon.server.exec.LogAndCheckHealth] Starting 6th build in daemon [uptime: 1 hrs 13 mins 18.595 secs, performance: 98%, no major garbage collections]
09:54:38.221 [INFO] [org.gradle.internal.work.DefaultWorkerLeaseService] Using 1 worker leases.
09:54:38.222 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for fileHashes, path C:\Users\[username-redacted]\Documents\[directoryname]\grobid\.gradle\4.2.1\fileHashes\fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@1f0217f
09:54:38.224 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for plugin-use-metadata, path C:\Users\[username-redacted]\.gradle\caches\4.2.1\plugin-resolution\plugin-use-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@5e4de3
09:54:38.224 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for client-status, path C:\Users\[username-redacted]\.gradle\caches\4.2.1\plugin-resolution\client-status.bin, access org.gradle.cache.internal.DefaultCacheAccess@5e4de3
09:54:38.226 [INFO] [org.gradle.internal.buildevents.BuildLogger] Starting Build
09:54:38.226 [DEBUG] [org.gradle.internal.buildevents.BuildLogger] Gradle user home: C:\Users\[usernameredacted]\.gradle
09:54:38.226 [DEBUG] [org.gradle.internal.buildevents.BuildLogger] Current dir: C:\Users\[usernameredacted]\Documents\[directoryredacted]\Software\git\grobid
09:54:38.226 [DEBUG] [org.gradle.internal.buildevents.BuildLogger] Settings file: null
09:54:38.226 [DEBUG] [org.gradle.internal.buildevents.BuildLogger] Build file: null
09:54:38.227 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Load build' started
09:54:38.228 [DEBUG] [org.gradle.initialization.buildsrc.BuildSourceBuilder] Starting to build the build sources.
09:54:38.228 [DEBUG] [org.gradle.initialization.buildsrc.BuildSourceBuilder] Gradle source dir does not exist. We leave.
09:54:38.228 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Evaluate settings' started
09:54:38.228 [DEBUG] [org.gradle.initialization.DefaultGradlePropertiesLoader] Found env project properties: []
09:54:38.228 [DEBUG] [org.gradle.initialization.DefaultGradlePropertiesLoader] Found system project properties: []
09:54:38.228 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Apply script settings.gradle to settings 'grobid'' started
09:54:38.229 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Apply script settings.gradle to settings 'grobid''
09:54:38.230 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Apply script settings.gradle to settings 'grobid'' completed
09:54:38.230 [DEBUG] [org.gradle.initialization.ScriptEvaluatingSettingsProcessor] Timing: Processing settings took: 0.001 secs
09:54:38.230 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Evaluate settings'
09:54:38.230 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Evaluate settings' completed
09:54:38.230 [INFO] [org.gradle.internal.buildevents.BuildLogger] Settings evaluated using settings file 'C:\Users\[usernameredacted]\Documents\[directory-redacted]\grobid\settings.gradle'.
09:54:38.230 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Load build'
09:54:38.230 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Load build' completed
09:54:38.230 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Configure build' started
09:54:38.231 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Load projects' started
....
09:54:38.328 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Resolve dependencies of :classpath' completed
09:54:38.332 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Build operation root.1.2.4 could not be started (1 worker(s) in use).
09:54:38.334 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Resolve gradle-release.jar (net.researchgate:gradle-release:2.6.0)' completed
....
09:54:38.242 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] Project :grobid-trainer - Registering model element 'schemaStore' (hidden = true)
09:54:38.242 [DEBUG] [org.gradle.initialization.ProjectPropertySettingBuildLoader] Looking for project properties from: C:\Users\[username-redacted]\\Documents\[directory-redacted]\grobid\gradle.properties
09:54:38.242 [DEBUG] [org.gradle.initialization.ProjectPropertySettingBuildLoader] Adding project properties (if not overwritten by user properties): [version, org.gradle.workers.max]
09:54:38.242 [DEBUG] [org.gradle.initialization.ProjectPropertySettingBuildLoader] Looking for project properties from: C:\Users\[username-redacted]\\Documents\[directory-redacted]\grobid\grobid-core\gradle.properties
09:54:38.243 [DEBUG] [org.gradle.initialization.ProjectPropertySettingBuildLoader] project property file does not exists. We continue!
09:54:38.243 [DEBUG] [org.gradle.initialization.ProjectPropertySettingBuildLoader] Looking for project properties from: C:\Users\[username-redacted]\\Documents\[directory-redacted]\grobid\grobid-home\gradle.properties
09:54:38.243 [DEBUG] [org.gradle.initialization.ProjectPropertySettingBuildLoader] project property file does not exists. We continue!
09:54:38.243 [DEBUG] [org.gradle.initialization.ProjectPropertySettingBuildLoader] Looking for project properties from: C:\Users\[username-redacted]\\Documents\[directory-redacted]\grobid\grobid-service\gradle.properties
09:54:38.243 [DEBUG] [org.gradle.initialization.ProjectPropertySettingBuildLoader] project property file does not exists. We continue!
09:54:38.243 [DEBUG] [org.gradle.initialization.ProjectPropertySettingBuildLoader] Looking for project properties from: C:\Users\[username-redacted]\\Documents\[directory-redacted]\grobid\grobid-trainer\gradle.properties
09:54:38.243 [DEBUG] [org.gradle.initialization.ProjectPropertySettingBuildLoader] project property file does not exists. We continue!
09:54:38.243 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Load projects'
09:54:38.243 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Load projects' completed
09:54:38.243 [INFO] [org.gradle.internal.buildevents.BuildLogger] Projects loaded. Root project using build file 'C:\Users\[username-redacted]\Documents\[directoryname]\grobid\build.gradle'.
09:54:38.243 [INFO] [org.gradle.internal.buildevents.BuildLogger] Included projects: [root project 'grobid', project ':grobid-core', project ':grobid-home', project ':grobid-service', project ':grobid-trainer']
...
09:54:38.244 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
> Configure project :
09:54:38.245 [INFO] [org.gradle.configuration.project.BuildScriptProcessor] Evaluating root project 'grobid' using build file 'C:\Users\[username-redacted]\Documents\[directoryname]\grobid\build.gradle'.
09:54:38.248 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for metadata-1.1/results, path C:\Users\[username-redacted]\.gradle\caches\transforms-1\metadata-1.1\results.bin, access org.gradle.cache.internal.DefaultCacheAccess@1357336
09:54:38.252 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for metadata-2.24/module-metadata, path C:\Users\[username-redacted]\.gradle\caches\modules-2\metadata-2.24\module-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@abb162
09:54:38.332 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for metadata-2.24/artifact-at-repository, path C:\Users\[username-redacted]\.gradle\caches\modules-2\metadata-2.24\artifact-at-repository.bin, access org.gradle.cache.internal.DefaultCacheAccess@abb162
09:54:38.556 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
09:54:38.557 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
> Configure project :grobid-core
09:54:38.557 [INFO] [org.gradle.configuration.project.BuildScriptProcessor] Evaluating project ':grobid-core' using build file 'C:\Users\[username-redacted]\Documents\[directoryname]\grobid\grobid-core\build.gradle'.
09:54:38.560 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
09:54:38.560 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
> Configure project :grobid-home
09:54:38.561 [INFO] [org.gradle.configuration.project.BuildScriptProcessor] Evaluating project ':grobid-home' using build file 'C:\Users\[username-redacted]\Documents\[directoryname]\grobid\grobid-home\build.gradle'.
09:54:38.562 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
09:54:38.562 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
> Configure project :grobid-service
09:54:38.562 [INFO] [org.gradle.configuration.project.BuildScriptProcessor] Evaluating project ':grobid-service' using build file 'C:\Users\[username-redacted]\Documents\[directoryname]\grobid\grobid-service\build.gradle'.
09:54:38.563 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
09:54:38.563 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
> Configure project :grobid-trainer
09:54:38.564 [INFO] [org.gradle.configuration.project.BuildScriptProcessor] Evaluating project ':grobid-trainer' using build file 'C:\Users\[username-redacted]\Documents\[directoryname]\grobid\grobid-trainer\build.gradle'.
09:54:38.566 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
09:54:38.566 [INFO] [org.gradle.internal.buildevents.BuildLogger] All projects evaluated.
09:54:38.603 [INFO] [org.gradle.execution.TaskNameResolvingBuildConfigurationAction] Selected primary task 'clean' from project :
09:54:38.604 [INFO] [org.gradle.execution.TaskNameResolvingBuildConfigurationAction] Selected primary task 'install' from project :
09:54:38.754 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for annotation-processors, path C:\Users\[username-redacted]\Documents\[directoryname]\grobid\.gradle\4.2.1\fileContent\annotation-processors.bin, access org.gradle.cache.internal.DefaultCacheAccess@9e9b51
09:54:38.819 [INFO] [org.gradle.internal.buildevents.BuildLogger] Tasks to be executed: [task ':clean', task ':grobid-core:clean', task ':grobid-home:clean', task ':grobid-service:clean', task ':grobid-trainer:clean', task ':grobid-core:compileJava', task ':grobid-core:processResources', task ':grobid-core:classes', task ':grobid-core:mainJar', task ':grobid-core:jar', task ':grobid-core:shadowJar', task ':grobid-core:sourceJar', task ':grobid-core:install', task ':grobid-home:compileJava', task ':grobid-home:processResources', task ':grobid-home:classes', task ':grobid-home:jar', task ':grobid-home:packageGrobidHome', task ':grobid-home:sourceJar', task ':grobid-home:install', task ':grobid-service:compileJava', task ':grobid-service:processResources', task ':grobid-service:classes', task ':grobid-service:jar', task ':grobid-service:startScripts', task ':grobid-service:distTar', task ':grobid-service:distZip', task ':grobid-service:sourceJar', task ':grobid-service:install', task ':grobid-trainer:compileJava', task ':grobid-trainer:processResources', task ':grobid-trainer:classes', task ':grobid-trainer:jar', task ':grobid-trainer:shadowJar', task ':grobid-trainer:sourceJar', task ':grobid-trainer:install']
09:54:38.843 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for resourceHashesCache, path C:\Users\[username-redacted]\Documents\[directoryname]\grobid\.gradle\4.2.1\fileHashes\resourceHashesCache.bin, access org.gradle.cache.internal.DefaultCacheAccess@1f0217f
09:54:38.843 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for fileSnapshots, path C:\Users\[username-redacted]\Documents\[directoryname]\grobid\.gradle\4.2.1\taskHistory\fileSnapshots.bin, access org.gradle.cache.internal.DefaultCacheAccess@136d5d0
09:54:38.844 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for taskHistory, path C:\Users\[username-redacted]\Documents\[directoryname]\grobid\.gradle\4.2.1\taskHistory\taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@136d5d0
09:54:38.845 [INFO] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for outputFiles, path C:\Users\[username-redacted]\Documents\[directoryname]\grobid\.gradle\buildOutputCleanup\outputFiles.bin, access org.gradle.cache.internal.DefaultCacheAccess@1ac80a8
09:54:38.847 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :clean (Thread[Daemon worker Thread 6,5,main]) started.
09:54:38.847 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
> Task :clean
09:54:38.848 [INFO] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Putting task artifact state for task ':clean' into context took 0.0 secs.
09:54:38.848 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':clean' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
09:54:38.850 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
09:54:38.850 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :clean (Thread[Daemon worker Thread 6,5,main]) completed. Took 0.002 secs.
09:54:38.850 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :grobid-core:clean (Thread[Daemon worker Thread 6,5,main]) started.
09:54:38.850 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
> Task :grobid-core:clean
09:54:38.851 [INFO] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Putting task artifact state for task ':grobid-core:clean' into context took 0.0 secs.
09:54:38.851 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':grobid-core:clean' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
09:54:38.854 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
09:54:38.854 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :grobid-core:clean (Thread[Daemon worker Thread 6,5,main]) completed. Took 0.003 secs.
09:54:38.855 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :grobid-home:clean (Thread[Daemon worker Thread 6,5,main]) started.
09:54:38.855 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
> Task :grobid-home:clean
09:54:38.856 [INFO] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Putting task artifact state for task ':grobid-home:clean' into context took 0.0 secs.
09:54:38.856 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':grobid-home:clean' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
09:54:38.857 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
09:54:38.857 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :grobid-home:clean (Thread[Daemon worker Thread 6,5,main]) completed. Took 0.001 secs.
09:54:38.858 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :grobid-service:clean (Thread[Daemon worker Thread 6,5,main]) started.
09:54:38.858 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
> Task :grobid-service:clean
09:54:38.858 [INFO] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Putting task artifact state for task ':grobid-service:clean' into context took 0.0 secs.
09:54:38.858 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':grobid-service:clean' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
09:54:38.859 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
09:54:38.859 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :grobid-service:clean (Thread[Daemon worker Thread 6,5,main]) completed. Took 0.001 secs.
09:54:38.860 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :grobid-trainer:clean (Thread[Daemon worker Thread 6,5,main]) started.
09:54:38.860 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
> Task :grobid-trainer:clean
09:54:38.860 [INFO] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Putting task artifact state for task ':grobid-trainer:clean' into context took 0.0 secs.
09:54:38.860 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':grobid-trainer:clean' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
09:54:38.861 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
09:54:38.861 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :grobid-trainer:clean (Thread[Daemon worker Thread 6,5,main]) completed. Took 0.001 secs.
09:54:38.862 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :grobid-core:compileJava (Thread[Daemon worker Thread 6,5,main]) started.
09:54:38.862 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
> Task :grobid-core:compileJava
09:54:38.862 [INFO] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Putting task artifact state for task ':grobid-core:compileJava' into context took 0.0 secs.
09:54:39.020 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':grobid-core:compileJava' (up-to-date check took 0.148 secs) due to:
  Task has failed previously.
09:54:39.024 [INFO] [org.gradle.api.internal.changedetection.changes.RebuildIncrementalTaskInputs] All input files are considered out-of-date for incremental task ':grobid-core:compileJava'.
09:54:39.049 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
09:54:39.052 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
09:54:39.052 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :grobid-core:compileJava (Thread[Daemon worker Thread 6,5,main]) completed. Took 0.189 secs.
09:54:39.053 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
09:54:39.054 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:54:39.054 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
09:54:39.054 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
09:54:39.054 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':grobid-core:compileJava'.
09:54:39.054 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not find tools.jar. Please check that C:\Program Files (x86)\Java\jre1.8.0_151 contains a valid JDK installation.
09:54:39.054 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
09:54:39.054 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
09:54:39.054 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
09:54:39.055 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
09:54:39.055 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
09:54:39.055 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
09:54:39.055 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 1s
09:54:39.055 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 6 actionable tasks: 2 executed, 4 up-to-date
<-------------> 0% WAITING
```

**Comment by kermitt2** [comment]
Hello, 

This error ("Could not find tools.jar") is usually due to the fact that you don't have a JDK but only a JRE installed on your machine. So you cannot build a Java project, you can only run an already built one. Building Grobid requires JDK 1.8. 

Note that if you simply want to play with the tool without the installation/build hassle, you can try the demo server -> http://grobid.science-miner.com

**Comment by wooooooooooooooowastaken** [comment]
I downloaded Java JDK 9 and updated the path in the environment variables but still get the same error.  Is there a difference between JDK 1.8 and JDK 9?  I appreciate the heads up about the demo site (would definitely be much easier!) but trying to use another software package that requires grobid in order to install (and their demo site is down at the moment).

**Comment by wooooooooooooooowastaken** [comment]
I needed to uninstall the previous version of Java and it compiled correctly! Thanks for the help!
