### ISSUE TITLE
Cannot parse recent Springer J Theor Phys PDF 

### ISSUE THREAD

**Issue by dksanyal** [kermitt2/grobid#277]
Hi,

GROBID cannot parse the attached PDF in latest GROBID build on CentOS (7.3.1611 (Core)). It fails with the following error.
However, the online version of GROBID shows the TEI file.
Any help is highly appreciated.

Jan 09, 2018 3:20:05 PM org.grobid.core.engines.ProcessEngine processFullTextDirectory
SEVERE: An error occured while processing the file /path/to/testcase/testfile.pdf. Continuing the process for the other files
org.grobid.core.exceptions.GrobidException: [TIMEOUT] PDF to XML conversion timed out
    at org.grobid.core.document.DocumentSource.processPdf2XmlThreadMode(DocumentSource.java:184)
    at org.grobid.core.document.DocumentSource.pdf2xml(DocumentSource.java:140)
    at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:63)
    at org.grobid.core.engines.FullTextParser.processing(FullTextParser.java:106)
    at org.grobid.core.engines.Engine.fullTextToTEIDoc(Engine.java:594)
    at org.grobid.core.engines.Engine.fullTextToTEI(Engine.java:583)
    at org.grobid.core.engines.ProcessEngine.processFullTextDirectory(ProcessEngine.java:181)
    at org.grobid.core.engines.ProcessEngine.processFullText(ProcessEngine.java:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.grobid.core.utilities.Utilities.launchMethod(Utilities.java:403)
    at org.grobid.core.main.batch.GrobidMain.main(GrobidMain.java:184)

Thanks,
Debarshi

**Comment by kermitt2** [comment]
Hello again ! Which version of GROBID do you use? Are you using the command line batch or the service? 
thanks

**Comment by dksanyal** [comment]
We used the latest version 0.5.0 in command line batch.
Online service works fine.

**Comment by dksanyal** [comment]
We made an interesting observation when running GROBID on this PDF in commandline mode WITHOUT BATCH. In that case, the correct TEI file is produced but the program does NOT terminate. This happens with many other PDF files.
Probably for this reason, when run in batch mode, it times out and proceeds to the next input file.
How can we solve the non-termination issue? Your help is much appreciated.

**Comment by kermitt2** [comment]
I've re-tested this PDF and it works fine for me both with the web service and the batch command line, including ending the JVM (v 0.5.5).
