### ISSUE TITLE
Building on CentOS 7 behind proxy fails

### ISSUE THREAD

**Issue by mrkafk** [kermitt2/grobid#292]
Building Grobid (0.5.1) on Centos with Oracle Java 8 fails in spite of setting proxy info in `gradle.properties`, either in `~/.gradle` or in project directory:

```
% ./gradlew -Djdk.http.auth.proxying.disabledSchemes="" clean install
Downloading https://services.gradle.org/distributions/gradle-4.2.1-all.zip

Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 authenticationrequired"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2142)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:60)
        at org.gradle.wrapper.Download.download(Download.java:45)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

I get exact same error when I build per docs with `./gradlew clean install`.

`gradle.properties`:

```
% cat gradle.properties
#Thu, 21 Apr 2016 18:39:55 +0200
version=0.6.0-SNAPSHOT
# Set workers to 1 that even for parallel builds it works. (I guess the shadow plugin makes some trouble)
org.gradle.workers.max=1



systemProp.http.proxyHost=myhost.com
systemProp.http.proxyPort=8080
systemProp.http.proxyUser=myuser
systemProp.http.proxyPassword=mypass
systemProp.http.nonProxyHosts=*.nonproxyrepos.com|localhos

systemProp.https.proxyHost=myhost.com
systemProp.https.proxyPort=8080
systemProp.https.proxyUser=myuser
systemProp.https.proxyPassword=mypass
systemProp.https.nonProxyHosts=*.nonproxyrepos.com|localhos
```

## However, when I build with Gradle 4.6 it all works without any problem:

`gradle clean install`

Environment:

```
% gradle --version

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Linux 2.6.32-696.el6.x86_64 amd64
```

**Comment by kermitt2** [comment]
Hello !

Modifying `gradle.properties` an/or `gradle-wrapper.properties` also did not work for me on ubuntu. 

The only working solution was to pass the proxy settings directly in the command line:
`./gradlew  -Dhttp.proxyHost=... -Dhttp.proxyPort=...  -Dhttps.proxyHost=... -Dhttps.proxyPort=... clean install`  

So I guess the best would be to update for using gradle 4.6 so that we can set the proxy info in the properties file.

**Comment by kermitt2** [comment]
The gradle version used by the gradle wrapper has been updated to 4.6 (ea843ccb49ae9bd71ec08e7d13abf9631696d0d8) and we can now set the proxy information in the `gradle.properties` file as expected.

**Comment by kermitt2** [comment]
So as this is fixed and is working well with my tests, I am closing the issue. Feel free to re-open it if you have any problems.
