### ISSUE TITLE
javax/xml/bind/ValidationException

### ISSUE THREAD

**Issue by seanrife** [kermitt2/grobid#342]
Getting the message `Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException`. Full error message:

```
Task :grobid-service:run
21:00:03.357 [main] WARN org.grobid.service.main.GrobidServiceApplication - Expected 2 arguments: [0]-server, [1]-<path to config.yaml>
21:00:03.360 [main] INFO org.grobid.service.main.GrobidServiceApplication - Found conf path: /opt/grobid/grobid-service/config/config.yaml
21:00:03.360 [main] WARN org.grobid.service.main.GrobidServiceApplication - Running with default arguments: "server" "/opt/grobid/grobid-service/config/config.yaml"
21:00:03.360 [main] INFO org.grobid.service.main.GrobidServiceApplication - Configuration file: /opt/grobid/grobid-service/config/config.yaml
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:129)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:106)
        at org.hibernate.validator.HibernateValidator.createSpecializedConfiguration(HibernateValidator.java:27)
        at org.hibernate.validator.HibernateValidator.createSpecializedConfiguration(HibernateValidator.java:24)
        at javax.validation.Validation$ProviderSpecificBootstrapImpl.configure(Validation.java:220)
        at io.dropwizard.validation.BaseValidator.newConfiguration(BaseValidator.java:32)
        at io.dropwizard.jersey.validation.Validators.newConfiguration(Validators.java:35)
        at io.dropwizard.jersey.validation.Validators.newValidatorFactory(Validators.java:27)
        at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:68)
        at io.dropwizard.Application.run(Application.java:72)
        at org.grobid.service.main.GrobidServiceApplication.main(GrobidServiceApplication.java:90)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 20 more
```

Runing:
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1, mixed mode)

I'm assuming this is related to an unmet dependency?

**Comment by kermitt2** [comment]
Hi Sean, thanks for the issue !

I think it is indeed an unmet dependency related to the fact that you are using Java 10. The JAXB APIs are no longer contained in the default classpath from Java 9. GROBID is compatible with Java 8. 

Well, Java was supposed to ensure backward compatibility, but they apparently took some freedom with that principle !  

I've just pushed a fix...

So, normally there are three simple possibilities: 
- you could downgrade to JDK 1.8 on your system
- as I added the JAXB dependency explicitly, you could update your local grobid master, rebuild and it should work
- if it is still not working, after updating your local grobid, uncomment the last line of the file `gradle.properties`, it will use the new `module` functionality of Java 9+ and load the dependency as a module

As I have not installed JDK 1.9 or Java 10, I have not tested myself these solutions :/

Thanks for the feedback!

**Comment by seanrife** [comment]
The fix you pushed worked! Thanks!
