### ISSUE TITLE
NullPointerException when files are not readable

### ISSUE THREAD

**Issue by liar666** [kermitt2/grobid#39]
Hi,

I just ran into a strange behaviour: when trying to access files in a dir (/tmp/ToTreat) that all belonged to another user, I ran into a not-really-explicatory-error: NullPointerException...

$ GROBID_HOME=/home/xxx/grobid/grobid-home/
$ DIR=/tmp/ToTreat/
$ java -Xmx1024m -Xms1024m \
    -jar ${GROBID_HOME}/../grobid-core/target/grobid-core-0.2.*.one-jar.jar \
    -gH ${GROBID_HOME} \
    -gP ${GROBID_HOME}/config/grobid.properties \
    -dIn ${DIR} -dOut ${DIR} \
    -exe processHeader
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.grobid.core.utilities.Utilities.launchMethod(Utilities.java:359)
        at org.grobid.core.main.batch.GrobidMain.main(GrobidMain.java:155)
        ... 6 more
Caused by: java.lang.NullPointerException
        at org.grobid.core.engines.ProcessEngine.processHeader(ProcessEngine.java:56)
        ... 12 more

**Comment by lfoppiano** [comment]
Seems to work fine when the directory is not accssible: 
```
Oct 17, 2018 3:58:49 PM org.grobid.core.engines.ProcessEngine processHeader
WARNING: No files in directory: /tmp/bao
```

On the other hand I've found that if the `-exe method` is supplied we have a NPE and I've pushed a fix.

**Comment by lfoppiano** [comment]
Closing as outdated ;-)
