### ISSUE TITLE
version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by liar666** [kermitt2/grobid#41]
Hi,

Under the latest up-to-date Debian GNU/Linux 7 (wheezy), I get the following exception when running grobid:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.grobid.core.utilities.Utilities.launchMethod(Utilities.java:359)
        at org.grobid.core.main.batch.GrobidMain.main(GrobidMain.java:154)
        ... 6 more
Caused by: java.lang.UnsatisfiedLinkError: /home/gmuller/grobid/grobid-home/lib/lin-64/libwapiti.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/gmuller/grobid/grobid-home/lib/lin-64/libwapiti.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
        at java.lang.Runtime.load0(Runtime.java:795)
        at java.lang.System.load(System.java:1062)
        at org.grobid.core.main.LibraryLoader.load(LibraryLoader.java:94)
        at org.grobid.core.factory.AbstractEngineFactory.init(AbstractEngineFactory.java:51)
        at org.grobid.core.factory.GrobidFactory.<init>(GrobidFactory.java:21)
        at org.grobid.core.factory.GrobidFactory.newInstance(GrobidFactory.java:58)
        at org.grobid.core.factory.GrobidFactory.getInstance(GrobidFactory.java:32)
        at org.grobid.core.engines.ProcessEngine.getEngine(ProcessEngine.java:42)
        at org.grobid.core.engines.ProcessEngine.processFullText(ProcessEngine.java:103)
        ... 12 more

The exact command executed is:
java -Xmx1024m -jar ~/grobid/grobid-core/target/grobid-core-0.3.0.one-jar.jar -gH ~/grobid/grobid-home/ -gP ~/grobid/grobid-home/config/grobid.properties -dIn In/ -dOut Out/ -exe processFullText

**Comment by liar666** [comment]
Hi again,

I got:
/home/gmuller/grobid/grobid-home/lib/lin-64/libwapiti.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/gmuller/grobid/grobid-home/lib/lin-64/libwapiti.so)
        linux-vdso.so.1 =>  (0x00007ffffef3b000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f72b23b4000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f72b2132000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f72b1f1b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f72b1b8f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f72b28e8000)

I've already tried to play with LD_LIBRARY_PATH and set it to point to grobid/grobid-home/lib/lin-64/ , but then every command coredumps, even 'ls'...

**Comment by kermitt2** [comment]
The Wapiti native library has been updated in the last commit. It should solve the issue because all the dependent libraries are now with the pre-compiled libwapiti.so (no need to modify LD_LIBRARY_PATH in any cases).

**Comment by liar666** [comment]
Hi,
I've updated the sources in my git repository and run the command again

It seems the wapiti-lib error has gone, since I can read on the terminal: 
[Wapiti] Loading model: "/home/gmuller/grobidNEW/grobid-home/models/fulltext/model.wapiti"
Model path: /home/gmuller/grobidNEW/grobid-home/models/fulltext/model.wapiti
[Wapiti] Loading model: "/home/gmuller/grobidNEW/grobid-home/models/segmentation/model.wapiti"
Model path: /home/gmuller/grobidNEW/grobid-home/models/segmentation/model.wapiti

So it seems the wapiti-lib error is gone. Thanks.

However, in the log I get:
[01/19/15-09:48:38] gmuller@verspertine:~/grobidNEW$ cat grobid.log 
19 Jan 2015 10:52.43 [INFO ] LibraryLoader             - Loading external native CRF library
19 Jan 2015 10:52.43 [INFO ] LibraryLoader             - Loading Wapiti native library...
19 Jan 2015 10:52.43 [INFO ] LibraryLoader             - Library crfpp loaded
19 Jan 2015 10:52.44 [INFO ] Lexicon                   - Initiating dictionary
19 Jan 2015 10:52.44 [INFO ] Lexicon                   - End of Initialization of dictionary
19 Jan 2015 10:52.44 [INFO ] Lexicon                   - Initiating names
19 Jan 2015 10:52.44 [INFO ] Lexicon                   - End of initialization of names
19 Jan 2015 10:52.45 [INFO ] Lexicon                   - Initiating country codes
19 Jan 2015 10:52.45 [INFO ] Lexicon                   - End of initialization of country codes
19 Jan 2015 10:52.46 [ERROR] ProcessEngine             - An error occured while processing the file /home/gmuller/grobidNEW/In/EP2270661A1.pdf. Continuing the process for the other files
19 Jan 2015 10:52.56 [ERROR] ProcessEngine             - An error occured while processing the file /home/gmuller/grobidNEW/In/820465381.pdf. Continuing the process for the other files
19 Jan 2015 10:52.57 [ERROR] ProcessEngine             - An error occured while processing the file /home/gmuller/grobidNEW/In/US7843296.pdf. Continuing the process for the other files
19 Jan 2015 10:53.01 [ERROR] ProcessEngine             - An error occured while processing the file /home/gmuller/grobidNEW/In/1309.7222.pdf. Continuing the process for the other files
19 Jan 2015 10:53.03 [ERROR] ProcessEngine             - An error occured while processing the file /home/gmuller/grobidNEW/In/US8420070.pdf. Continuing the process for the other files

Whereas the files are valid patents & papers...

**Comment by kermitt2** [comment]
Thanks for the feedback! 

This is an other type of error, I will close this issue, but can you send me maybe per email these problematic PDF so that I can look what's going on with them? 
Is it just a couple of PDFs among a large number of them or it happens for you for each pdf? 
See you!
