### ISSUE TITLE
Header model evaluation data encoding issue, failing with JEP

### ISSUE THREAD

**Issue by de-code** [kermitt2/grobid#466]
Hi @kermitt2

The header model evaluation data has some _odd_ characters in [grobid-trainer/resources/dataset/header/evaluation/headers/322._499236.header](https://github.com/kermitt2/grobid/blob/master/grobid-trainer/resources/dataset/header/evaluation/headers/322._499236.header) which causes issues later on (see below). It is the line after the first `2n 2n...`:

```
tilings tilings t ti til tili s gs ngs ings BLOCKEND LINEEND SAMEFONT SAMEFONTSIZE 0 0 0 NOCAPS NODIGIT 0 0 0 0 0 0 0 0 0 0 NOPUNCT 0 0
of of o of of of f of of of BLOCKSTART LINESTART SAMEFONT SAMEFONTSIZE 0 0 0 NOCAPS NODIGIT 0 0 1 0 0 0 0 0 0 0 NOPUNCT 0 0
a a a a a a a a a a BLOCKIN LINEIN SAMEFONT SAMEFONTSIZE 0 0 0 NOCAPS NODIGIT 1 0 1 0 0 0 0 0 0 0 NOPUNCT 0 0
2n 2n 2 2n 2n 2n n 2n 2n 2n BLOCKIN LINEIN SAMEFONT SAMEFONTSIZE 0 0 0 NOCAPS CONTAINSDIGITS 0 0 0 0 0 0 0 0 0 0 NOPUNCT 0 0
񮽙 񮽙 ? 񮽙 񮽙 񮽙 ? 񮽙 񮽙 񮽙 BLOCKIN LINEIN SAMEFONT HIGHERFONT 0 0 0 ALLCAP NODIGIT 0 0 0 0 0 0 0 0 0 0 NOPUNCT 0 0
2n 2n 2 2n 2n 2n n 2n 2n 2n BLOCKIN LINEIN SAMEFONT LOWERFONT 0 0 0 NOCAPS CONTAINSDIGITS 0 0 0 0 0 0 0 0 0 0 NOPUNCT 0 0
```

The related section from [grobid-trainer/resources/dataset/header/evaluation/tei/header317.tei](https://github.com/kermitt2/grobid/blob/master/grobid-trainer/resources/dataset/header/evaluation/tei/header317.tei) doesn't seem to show the same encoding issue.

```
are all domino tilings of a 2n fi 2n chessboard
```

This is then failing with the JEP integration, trying to set the `input` variable.

```
Jul 26, 2019 11:53:33 AM org.grobid.core.jni.DeLFTModel$LabelTask call
SEVERE: DeLFT model labelling via JEP failed
Labeling took: 9 msjep.JepException: <class 'UnicodeDecodeError'>: utf-8

        at jep.Jep.set(Native Method)
        at jep.Jep.set(Jep.java:786)
        at org.grobid.core.jni.DeLFTModel$LabelTask.call(DeLFTModel.java:87)
        at org.grobid.core.jni.DeLFTModel$LabelTask.call(DeLFTModel.java:66)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

(ignore line numbers, as I have made changes to add debug info)

Loading the file from Python works fine. It does show the characters being in an odd range:

```
>>> Path('grobid-trainer/resources/dataset/header/evaluation/headers/322._499236.header').read_text(encoding='utf-8').splitlines()[33]
'\U0006ef59 \U0006ef59 ? \U0006ef59 \U0006ef59 \U0006ef59 ? \U0006ef59 \U0006ef59 \U0006ef59 BLOCKIN LINEIN SAMEFONT HIGHERFONT 0 0 0 ALLCAP NODIGIT 0 0 0 0 0 0 0 0 0 0 NOPUNCT 0 0'
```

I suppose there are two solutions:
- fix the data as that seems to be an incorrect character
- let Python load the data from the file that is generated anyway

**Comment by kermitt2** [comment]
I merged the fix of PR  #468 ! Thanks a lot @de-code
