### ISSUE TITLE
Exception processing PDF with bad character encoding (0.5.4+)

### ISSUE THREAD

**Issue by de-code** [kermitt2/grobid#472]
When processing a PDF that has bad character encoding, GROBID now responds with error 500 because it can't parse the generated LXML:

```
ERROR [2019-07-29 15:19:19,034] org.grobid.service.process.GrobidRestProcessFiles: An unexpected exception occurs. 
! org.apache.xerces.impl.io.MalformedByteSequenceException: Invalid byte 2 of 3-byte UTF-8 sequence.
! at org.apache.xerces.impl.io.UTF8Reader.invalidByte(Unknown Source)
! at org.apache.xerces.impl.io.UTF8Reader.read(Unknown Source)
! at org.apache.xerces.impl.XMLEntityScanner.load(Unknown Source)
! at org.apache.xerces.impl.XMLEntityScanner.scanLiteral(Unknown Source)
! at org.apache.xerces.impl.XMLScanner.scanAttributeValue(Unknown Source)
! at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanAttribute(Unknown Source)
! at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
! ... 80 common frames omitted
! Causing: org.xml.sax.SAXParseException: Invalid byte 2 of 3-byte UTF-8 sequence.
! at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
! at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
! at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
! at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
! at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
! at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
! at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
! at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
! at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
! at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
! at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
! at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
! at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
! at org.grobid.core.document.Document.addTokenizedDocument(Document.java:385)
! ... 70 common frames omitted
! Causing: org.grobid.core.exceptions.GrobidException: [PARSING_ERROR] Cannot parse file: /path/to/grobid/grobid-home/tmp/PwmNNKmeZ2.lxml
! at org.grobid.core.document.Document.addTokenizedDocument(Document.java:404)
```

xmllint isn't happy either:

```console
$ xmllint special-characters.lxml 
/home/deuser/_git_/elife/pdf-xml/data/elife/issues/issues-grobid-0.5.4-plus-conversion/sample/special-characters.lxml:3: parser error : Char 0xD835 out of allowed range
font0"/><SP WIDTH="2.75" VPOS="72.35" HPOS="83.25"/><String ID="p1_w2" CONTENT="
                                                                               ^
/home/deuser/_git_/elife/pdf-xml/data/elife/issues/issues-grobid-0.5.4-plus-conversion/sample/special-characters.lxml:3: parser error : invalid character in attribute value
font0"/><SP WIDTH="2.75" VPOS="72.35" HPOS="83.25"/><String ID="p1_w2" CONTENT="
                                                                               ^
/home/deuser/_git_/elife/pdf-xml/data/elife/issues/issues-grobid-0.5.4-plus-conversion/sample/special-characters.lxml:3: parser error : attributes construct error
font0"/><SP WIDTH="2.75" VPOS="72.35" HPOS="83.25"/><String ID="p1_w2" CONTENT="
                                                                               ^
/home/deuser/_git_/elife/pdf-xml/data/elife/issues/issues-grobid-0.5.4-plus-conversion/sample/special-characters.lxml:3: parser error : Couldn't find end of Start Tag String line 3
font0"/><SP WIDTH="2.75" VPOS="72.35" HPOS="83.25"/><String ID="p1_w2" CONTENT="
                                                                               ^
/home/deuser/_git_/elife/pdf-xml/data/elife/issues/issues-grobid-0.5.4-plus-conversion/sample/special-characters.lxml:3: parser error : Char 0xD835 out of allowed range
font0"/><SP WIDTH="2.75" VPOS="72.35" HPOS="83.25"/><String ID="p1_w2" CONTENT="
                                                                               ^
/home/deuser/_git_/elife/pdf-xml/data/elife/issues/issues-grobid-0.5.4-plus-conversion/sample/special-characters.lxml:3: parser error : PCDATA invalid Char value 55349
font0"/><SP WIDTH="2.75" VPOS="72.35" HPOS="83.25"/><String ID="p1_w2" CONTENT="
                                                                               ^
```

In GROBID 0.5.3 the string is extracted as `10 í µg of special characters` which is also what is in the LXML for the latest version.

There is obviously an issue further in the document conversion. And in this case it seems to stem from the `.docx` file to use a Windows font that wasn't available when it was converted to `.pdf`. But it would be nice if it extracted what it could.

Files:
[special-characters.docx](https://github.com/kermitt2/grobid/files/3442999/special-characters.docx)
[special-characters-bad-character-encoding.pdf](https://github.com/kermitt2/grobid/files/3443001/special-characters-bad-character-encoding.pdf)
[special-characters.lxml.zip](https://github.com/kermitt2/grobid/files/3443006/special-characters.lxml.zip)

**Comment by lfoppiano** [comment]
The difference with previous versions, could be related with pdfalto?

**Comment by kermitt2** [comment]
It's actually an issue primarily for `pdfalto`. `pdfalto` should detect all invalid character codes - so if we have something which cannot be solved into a correct UTF-8 code, for some various reasons, we should have a place holder and not propagate some invalid unicode range to the ALTO file. Why it's not working here is unclear at first look, and it requires to look at the character encoding with pdfalto.

**Comment by Aazhar** [comment]
Hello,
I don't know where to comment about this issue, but as far as I remember, I've added an option in pdfalto (-ocr)  which is meant to recognize such characters, since I didn't make much improvements regarding the ocr, those chars are replaced with some placeholders.
I need to do some tests to make sure

**Comment by lfoppiano** [comment]
Few years later it seems this issue is no longer reproducible 🎉 

[out.xml](https://github.com/user-attachments/files/26212923/out.xml)
