### ISSUE TITLE
Update Jep to 3.9.0

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#529]
As in the title ;-) might have improved some of the glitches with the previous version. 

https://github.com/ninia/jep/releases/tag/v3.9.0

Although I could not find the latest changes or a release notel...

**Comment by lfoppiano** [comment]
With jdk 13 and 14, we've got the following issue: 
```
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  [2020-06-30 04:04:45,306] com.hubspot.dropwizard.guicier.DropwizardModule: Added guice injected health check: org.grobid.service.resources.HealthResource
INFO  [2020-06-30 04:04:45,311] org.grobid.core.utilities.GrobidProperties: environment variables overrides: {}
INFO  [2020-06-30 04:04:45,313] org.grobid.service.GrobidRestService: Initiating Servlet GrobidRestService
INFO  [2020-06-30 04:04:45,314] org.grobid.core.main.LibraryLoader: Loading external native sequence labelling library
INFO  [2020-06-30 04:04:45,315] org.grobid.core.main.LibraryLoader: Loading Wapiti native library...
INFO  [2020-06-30 04:04:45,316] org.grobid.core.main.LibraryLoader: Loading JEP native library for DeLFT... /Users/lfoppiano/development/projects/grobid/grobid-home/lib/mac-64
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, org.grobid.core.exceptions.GrobidException: [GENERAL] Loading JEP native library for DeLFT failed
  at org.grobid.service.GrobidRestService.<init>(GrobidRestService.java:69)
  at org.grobid.service.modules.GrobidServiceModule.configure(GrobidServiceModule.java:30) (via modules: com.google.inject.util.Modules$CombinedModule -> org.grobid.service.modules.GrobidServiceModule)
  while locating org.grobid.service.GrobidRestService

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at com.hubspot.dropwizard.guicier.GuiceBundle$Builder.lambda$new$0(GuiceBundle.java:152)
        at com.hubspot.dropwizard.guicier.GuiceBundle.run(GuiceBundle.java:106)
        at com.hubspot.dropwizard.guicier.GuiceBundle.run(GuiceBundle.java:34)
        at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at org.grobid.service.main.GrobidServiceApplication.main(GrobidServiceApplication.java:107)
Caused by: org.grobid.core.exceptions.GrobidException: [GENERAL] Loading JEP native library for DeLFT failed
        at org.grobid.core.main.LibraryLoader.load(LibraryLoader.java:177)
        at org.grobid.core.factory.AbstractEngineFactory.init(AbstractEngineFactory.java:68)
        at org.grobid.service.GrobidRestService.<init>(GrobidRestService.java:79)
        at org.grobid.service.GrobidRestService$$FastClassByGuice$$d8fc2784.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        ... 12 more
Caused by: java.lang.NoSuchFieldException: usr_paths
        at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
        at org.grobid.core.main.LibraryLoader.addLibraryPath(LibraryLoader.java:188)
        at org.grobid.core.main.LibraryLoader.load(LibraryLoader.java:149)
        ... 29 more
```

**Comment by lfoppiano** [comment]
```
   public static void addLibraryPath(String pathToAdd) throws Exception {
        Field usrPathsField = ClassLoader.class.getDeclaredField("usr_paths");
        usrPathsField.setAccessible(true);
[...]
```

**Comment by lfoppiano** [comment]
https://stackoverflow.com/questions/56039341/get-declared-fields-of-java-lang-reflect-fields-in-jdk12
