### ISSUE TITLE
Error case. ProcessPdfToXml: pdftoxml process finished with error code: 143.

### ISSUE THREAD

**Issue by xmlyqing00** [kermitt2/grobid#613]
Hi everyone, 

Thanks for such a great project. I found a problem when I try to process a PDF (see the attachment) by python client. The command is processFulltextDocument. 

I tried both my local GROBID server and the web demo server. Got the same issue: **failed with error 500**. The log messages are here:

127.0.0.1 - - [30/Jul/2020:15:46:22 +0000] "POST /api/processFulltextDocument HTTP/1.1" 500 41 "-" "python-requests/2.23.0" 20045
127.0.0.1 - - [30/Jul/2020:15:50:35 +0000] "GET /api/isalive HTTP/1.1" 200 4 "-" "python-requests/2.23.0" 3
INFO  [2020-07-30 15:50:35,945] org.grobid.core.factory.GrobidPoolingFactory: Number of Engines in pool active/max: 1/10
ERROR [2020-07-30 15:50:55,984] **org.grobid.core.process.ProcessPdfToXml: pdftoxml process finished with error code: 143.** [/Ship03/Sources/grobid/grobid-home/pdf2xml/l
in-64/pdfalto_server, -blocks, -noImageInline, -fullFontName, -noImage, -annotation, -filesLimit, 2000, /Ship03/Sources/grobid/grobid-home/tmp/origin18295561640565011
165.pdf, /Ship03/Sources/grobid/grobid-home/tmp/XYGtk9h2nT.lxml]
ERROR [2020-07-30 15:50:55,985] org.grobid.core.process.ProcessPdfToXml: pdftoxml return message:
Syntax Error (726217): Unknown operator '<04><a4><1a><91>2<b3>X<01>u'
Syntax Error (726219): Unknown operator '<b1><af>h<de>Z<a2>D@<f3>|<93><e7>Gx<96>r<08><f8><c8>*hT<91><99><07><91><a2>`<91><c9><b4><a8>0e,<ca><ee>'

Syntax Error (726233): Unknown operator '<b5><04>'
Syntax Error (726244): Unknown operator ';<a6>Zaz<f6><fa><c9>v<85>:'
Syntax Error (726784): Unknown operator 'A'
Syntax Error (726792): Unknown operator '~"<b5><92>U<b5>4<a6><f9><86>'
Syntax Error (726842): Unknown operator '<13><a8><bd><e5>So<1f><d9>'
Syntax Error (726847): Unknown operator 'kY<c3><b3><8c><ce><e6><9b>3<86>'
Syntax Error (726937): Unknown operator '<af><ee>$E<a2>'
Syntax Error (726976): Illegal character ')'
Syntax Error (727122): Illegal character '{'
Syntax Error (727122): Unknown operator 't<e4>I<99>J<ba><ad><b6><0b><9f><bc>8X<9b><d4>|<91><bb><da>1<a7><80><b4>B<f3><c0><a3><08><1e><b5>Fv2z"A<e1><e0>k<e2><a5>+'
Syntax Error (727130): Unknown operator 'G<c3><90>K<01>t<cc>`<08><18><8e><c8><b8><b8>'
Syntax Error (727319): Unknown operator '+<b9><dc>O<19><08><89><c1>'
Syntax Error (727324): Unknown operator '<01><8f>F<0f><fd><e7><e6>z<b3><eb>UwN<bd><a8><df><96><f2>8J<04><e7>"w<ae>Hq<a1>'
Syntax Error (727326): Unknown operator ':<ca><1c><c1>2'
Syntax Error (727333): Illegal character '{'
Syntax Error (727364): Illegal character '}'
Syntax Error (727386): Illegal character '}'
Syntax Error (727389): Illegal character '>'
Syntax Error (727395): Illegal character '>'
Syntax Error (727652): Illegal character '}'
Syntax Error (727663): Illegal character '}'
Syntax Error (727692): Illegal character '{'
Syntax Error (727722): Illegal character '{'
Syntax Error (727742): Illegal character '>'
...................
...................                                                                                                                           
ERROR [2020-07-30 15:50:55,985] org.grobid.service.process.GrobidRestProcessFiles: An unexpected exception occurs.                                                    
! org.grobid.core.exceptions.GrobidException: [TIMEOUT] PDF to XML conversion timed out                                                                               
! at org.grobid.core.document.DocumentSource.processPdfToXmlServerMode(DocumentSource.java:237)                                                                       
! at org.grobid.core.document.DocumentSource.pdf2xml(DocumentSource.java:146)                                                                                         
! at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:63)                                                                                          
! at org.grobid.core.engines.FullTextParser.processing(FullTextParser.java:111)                                                                                       
! at org.grobid.core.engines.Engine.fullTextToTEIDoc(Engine.java:489)                                                                                                 
! at org.grobid.core.engines.Engine.fullTextToTEI(Engine.java:480)                        

I put the pdf file here for debugging. Thank you for your time.
[Quan_Equiangular_Kernel_Dictionary_CVPR_2016_paper.pdf](https://github.com/kermitt2/grobid/files/5002562/Quan_Equiangular_Kernel_Dictionary_CVPR_2016_paper.pdf)

**Comment by lfoppiano** [comment]
Dear @xmlyqing00, the first case (1) NO_BLOCKS is actually the correct behavior. These two pdfs are failing with a reason, there is effectively no content to be extracted as they are composed of images. We shall documents these errors, indeed.

**Comment by xmlyqing00** [comment]
> Dear @xmlyqing00, the first case (1) NO_BLOCKS is actually the correct behavior. These two pdfs are failing with a reason, there is effectively no content to be extracted as they are composed of images. We shall documents these errors, indeed.

Interesting. You are right. I didn't notice that the first two pdfs are composed of images.  Thanks.

**Comment by lfoppiano** [comment]
For the second problem, it seems an issue with pdfalto.

**Comment by xmlyqing00** [comment]
> For the second problem, it seems an issue with pdfalto.

Thanks for your reply. Appreciate.
