### ISSUE TITLE
Facing errors while running the Java Example 

### ISSUE THREAD

**Issue by navraj28** [kermitt2/grobid#633]
Hello!
    I am trying to run the Java example, as [per](https://github.com/kermitt2/grobid-example). I built Grobid against the Master branch.
    I see that signature of Engine.processHeader has changed from boolean to int. I tried both 0 & 1. `engine.processHeader(pdfPath, 0, resHeader);`

    I am getting the below stack-trace:
```
INFO: Loading model: D:\grobid\grobid-home\models\header\model.wapiti (size: 15734670)
org.grobid.core.exceptions.GrobidException: [PDFTOXML_CONVERSION_FAILURE] PDF to XML conversion failed on pdf file .\src\test\resources\Wang_paperAVE2008.pdf 
null
	at org.grobid.core.document.DocumentSource.processPdfToXmlThreadMode(DocumentSource.java:208)
	at org.grobid.core.document.DocumentSource.pdf2xml(DocumentSource.java:154)
	at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:63)
	at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:49)
	at org.grobid.core.engines.HeaderParser.processing(HeaderParser.java:101)
	at org.grobid.core.engines.Engine.processHeader(Engine.java:385)
	at org.grobid.core.engines.Engine.processHeader(Engine.java:374)
	at org.grobidExample.MyGrobid.runGrobid(MyGrobid.java:38)
	at org.grobidExample.App.main(App.java:11)
[Wapiti] Loading model: "D:\grobid\grobid-home\models\header\model.wapiti"
Model path: D:\grobid\grobid-home\models\header\model.wapiti

```

**Comment by kermitt2** [comment]
Hello @navraj28 
As indicated in the documentation, the latest release (0.6.1) and current master do not support the Windows platform, pdfalto has not been recompiled for this platform. You will need to use the docker image to have it running on Windows.

**Comment by lfoppiano** [comment]
@navraj28 https://grobid.readthedocs.io/en/latest/Troubleshooting/#windows-related-issues

You can use the docker image and the java/python client

**Comment by navraj28** [comment]
@lfoppiano Strangely, I am able to run the almost exact same code in the Unit Tests (_TestHeaderParser.testHeaderHeader_), but not the example Java API code.

**Comment by kermitt2** [comment]
@navraj28 it's not strange, the test isolates the process from pdfalto and from the stuff outside the HeaderParser class (the unit of the test).

**Comment by navraj28** [comment]
Thank you @kermitt2

**Comment by siggins** [comment]
Are there plans to have it working again on Windows? I'm unable to update past 0.6.0 at present

**Comment by lfoppiano** [comment]
@siggins we can't ensure the compatibility with Windows as the work to maintain all the three OS is quite big, however, we would be happy to get help from someone more familiar with it.

**Comment by siggins** [comment]
What's needed to get support working again on Windows? I may be able to help

**Comment by kermitt2** [comment]
Hi @siggins ! Currently the only piece missing for Windows is to recompile [pdfalto](https://github.com/kermitt2/pdfalto) binary (using Cygwin) and move it under `grobid-home/pdf2xml/win-64/pdfalto/`.

**Comment by lfoppiano** [comment]
@siggins any luck? I remember I spent a good week building the last version 😓
