### ISSUE TITLE
Empty data is provided to Wapiti tagger: java.lang.Throwable

### ISSUE THREAD

**Issue by liar666** [kermitt2/grobid#78]
On one of paper (available here: http://guillaumemuller1.free.fr/Articles/grizard_AAMAS_COIN_2006.pdf) I get the following Exception:

Empty data is provided to Wapiti tagger: java.lang.Throwable
        at org.grobid.core.jni.WapitiWrapper.label(WapitiWrapper.java:18)
        at org.grobid.core.jni.WapitiModel.label(WapitiModel.java:48)
        at org.grobid.core.engines.tagging.WapitiTagger.label(WapitiTagger.java:28)
        at org.grobid.core.engines.AbstractParser.label(AbstractParser.java:39)
        at org.grobid.core.engines.FullTextParser.processing(FullTextParser.java:150)
        at org.grobid.core.engines.Engine.fullTextToTEI(Engine.java:574)
        at org.grobid.core.engines.ProcessEngine.processFullTextDirectory(ProcessEngine.java:163)
        at org.grobid.core.engines.ProcessEngine.processFullText(ProcessEngine.java:145)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.grobid.core.utilities.Utilities.launchMethod(Utilities.java:359)
        at org.grobid.core.main.batch.GrobidMain.main(GrobidMain.java:166)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)

This is not really important since I get a TEI with sufficient information, but just in case this would hide another problem...

**Comment by lfoppiano** [comment]
Hi @liar666 , I've tested your pdf with the latest GROBID version, trying to extract the fulltext. I did not get the error. 
Could you maybe give it another try with the latest version and tell if the exception is still occurring? 

Thanks

**Comment by liar666** [comment]
Just tested with latest code from git repo.

That Works ! Thanks !
