### ISSUE TITLE
Wrong schema

### ISSUE THREAD

**Issue by elonzh** [kermitt2/grobid#788]
## Request

![image](https://user-images.githubusercontent.com/8749411/124222678-c97b1080-db34-11eb-86fd-d158cc69c5e9.png)

## TEI Result

https://gist.github.com/elonzh/ceaf26ef4c011e5b3f57d59eaf044a8d

## Reproduce

```python
import logging

from lxml import etree

xsd_schema_path = "scholardata/grobid/schemas/xsd/Grobid.xsd"
xsd_schema = etree.XMLSchema(etree.parse(xsd_schema_path))

rng_schema_path = "scholardata/grobid/schemas/rng/Grobid.rng"
rng_schema = etree.RelaxNG(etree.parse(rng_schema_path))

xml_path = "Investigation of isospin-triplet and isospin-singlet pairing in wave function.pdf.tei.xml"
doc = etree.parse(xml_path)

try:
    xsd_schema.assertValid(doc)
except etree.DocumentInvalid as e:
    logging.error(e, exc_info=True)

try:
    rng_schema.assertValid(doc)
except etree.DocumentInvalid as e:
    logging.error(e, exc_info=True)
```

```text
ERROR:root:Element '{http://www.tei-c.org/ns/1.0}idno': This element is not expected. Expected is one of ( {http://www.tei-c.org/ns/1.0}series, {http://www.tei-c.org/ns/1.0}monogr, {http://www.tei-c.org/ns/1.0}ptr, {http://www.tei-c.org/ns/1.0}ref, {http://www.tei-c.org/ns/1.0}note )., line 215
Traceback (most recent call last):
  File "<ipython-input-24-0c6234465d8e>", line 14, in <module>
    xsd_schema.assertValid(doc)
  File "src\lxml\etree.pyx", line 3623, in lxml.etree._Validator.assertValid
lxml.etree.DocumentInvalid: Element '{http://www.tei-c.org/ns/1.0}idno': This element is not expected. Expected is one of ( {http://www.tei-c.org/ns/1.0}series, {http://www.tei-c.org/ns/1.0}monogr, {http://www.tei-c.org/ns/1.0}ptr, {http://www.tei-c.org/ns/1.0}ref, {http://www.tei-c.org/ns/1.0}note )., line 215
ERROR:root:Did not expect element idno there, line 215
Traceback (most recent call last):
  File "<ipython-input-24-0c6234465d8e>", line 19, in <module>
    rng_schema.assertValid(doc)
  File "src\lxml\etree.pyx", line 3623, in lxml.etree._Validator.assertValid
lxml.etree.DocumentInvalid: Did not expect element idno there, line 215
```

**Comment by kermitt2** [comment]
Thank you @elonzh ! 

I need to add this in the customized schema. 

This is problem of the standard TEI: it can't go under `<monogr>` because the DOI would refer to the full item containing the article (not the DOI of the article), and it cannot really go under `<analytic>` neither because the definition is: 

> <analytic> (analytic level) contains bibliographic elements describing an item (e.g. an article or poem) published within a monograph or journal and not as an independent publication.

And the point of the DOI is to have the article as independent online electronic publication.

**Comment by kermitt2** [comment]
The schemas have been updated with f1265a140d7c7eb231e5d1b6280480f2e6a271a7 and everything looks good:

```
lopez@work:~/grobid$ xmllint --noout --schema grobid-home/schemas/xsd/Grobid.xsd ~/Downloads/PhysRevC.100.014306\(1\).pdf.tei.xml 
/home/lopez/Downloads/PhysRevC.100.014306.tei.xml validates
```
