### ISSUE TITLE
Deep Learning model for header needs to be updated

### ISSUE THREAD

**Issue by anafandon** [kermitt2/grobid#843]
Hi, and congrats on your great work with Grobid.
I managed to set up Grobid with the docker image you provide on this [guide](https://grobid.readthedocs.io/en/latest/Grobid-docker/#crf-and-deep-learning-image) 

Everything works perfect until I want to switch to deep learning models. I set up the yaml file as you mentioned in the guide and the  I run the following command WITHOUT the --gpus all flag since my machine (linux) doesn't have gpus) 

> sudo docker run --rm --init -p 8080:8070 -p 8081:8071 -v /home/ubuntu/grobid_client_python/grobid.yaml:/opt/grobid/grobid-home/config/grobid.yaml:ro  grobid/grobid:0.7.1-SNAPSHOT

but the following error pops out:
```
loading model weights /opt/grobid/grobid-home/models/affiliation-address-BidLSTM_CRF_FEATURES/model_weights.hdf5
2021-10-19 15:23:19.286134: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (-1)
INFO  [2021-10-19 15:23:19,662] org.grobid.core.jni.DeLFTModel: Loading DeLFT model for name-header with architecture BidLSTM_CRF_FEATURES...
running thread: 23
loading model weights /opt/grobid/grobid-home/models/name-header-BidLSTM_CRF_FEATURES/model_weights.hdf5
running thread: 23
INFO  [2021-10-19 15:23:22,631] org.grobid.core.jni.DeLFTModel: Loading DeLFT model for name-citation with architecture BidLSTM_CRF_FEATURES...
loading model weights /opt/grobid/grobid-home/models/name-citation-BidLSTM_CRF_FEATURES/model_weights.hdf5
INFO  [2021-10-19 15:23:25,761] org.grobid.core.jni.DeLFTModel: Loading DeLFT model for header with architecture BidLSTM_CRF_FEATURES...
running thread: 23
loading model weights /opt/grobid/grobid-home/models/header-BidLSTM_CRF_FEATURES/model_weights.hdf5
running thread: 23
INFO  [2021-10-19 15:23:29,314] org.grobid.core.jni.DeLFTModel: Loading DeLFT model for date with architecture BidLSTM_CRF_FEATURES...
loading model weights /opt/grobid/grobid-home/models/date-BidLSTM_CRF_FEATURES/model_weights.hdf5
running thread: 23
INFO  [2021-10-19 15:23:33,058] org.grobid.core.jni.DeLFTModel: Loading DeLFT model for citation with architecture BidLSTM_CRF_FEATURES...
loading model weights /opt/grobid/grobid-home/models/citation-BidLSTM_CRF_FEATURES/model_weights.hdf5
INFO  [2021-10-19 15:23:37,327] org.grobid.core.jni.WapitiModel: Loading model: /opt/grobid/grobid-home/models/fulltext/model.wapiti (size: 26707735)
[Wapiti] Loading model: "/opt/grobid/grobid-home/models/fulltext/model.wapiti"
Model path: /opt/grobid/grobid-home/models/fulltext/model.wapiti
INFO  [2021-10-19 15:23:41,123] org.grobid.core.jni.WapitiModel: Loading model: /opt/grobid/grobid-home/models/segmentation/model.wapiti (size: 31133177)
[Wapiti] Loading model: "/opt/grobid/grobid-home/models/segmentation/model.wapiti"
Model path: /opt/grobid/grobid-home/models/segmentation/model.wapiti
running thread: 23
INFO  [2021-10-19 15:23:46,156] org.grobid.core.jni.DeLFTModel: Loading DeLFT model for reference-segmenter with architecture BidLSTM_CRF_FEATURES...
running thread: 23
INFO  [2021-10-19 15:23:46,158] org.grobid.core.jni.DeLFTModel: Loading DeLFT model for figure with architecture BidLSTM_CRF_FEATURES...
running thread: 23
INFO  [2021-10-19 15:23:46,160] org.grobid.core.jni.DeLFTModel: Loading DeLFT model for table with architecture BidLSTM_CRF_FEATURES...
INFO  [2021-10-19 15:23:46,162] org.grobid.core.factory.GrobidPoolingFactory: Number of Engines in pool active/max: 1/10
ERROR [2021-10-19 15:24:09,635] org.grobid.core.jni.DeLFTModel: DeLFT model labelling via JEP failed
! jep.JepException: <class 'ValueError'>: Error when checking input: expected features_input to have shape (None, 22) but got array with shape (212, 21)
! at /usr/local/lib/python3.6/dist-packages/keras/engine/training_utils.standardize_input_data(training_utils.py:138)
! at /usr/local/lib/python3.6/dist-packages/keras/engine/training._standardize_user_data(training.py:751)
! at /usr/local/lib/python3.6/dist-packages/keras/engine/training.predict_on_batch(training.py:1268)
! at /usr/local/lib/python3.6/dist-packages/delft/sequenceLabelling/tagger.tag(tagger.py:85)
! at /usr/local/lib/python3.6/dist-packages/delft/sequenceLabelling/wrapper.tag(wrapper.py:391)
! at <string>.<module>(<string>:1)
! at jep.Jep.getValue(Native Method)
! at jep.Jep.getValue(Jep.java:487)
! at org.grobid.core.jni.DeLFTModel$LabelTask.call(DeLFTModel.java:127)
! at org.grobid.core.jni.DeLFTModel$LabelTask.call(DeLFTModel.java:81)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)

```

**Comment by lfoppiano** [comment]
In brief, not all the models used in Grobid exists for deep learning and few are not available in the architecture that is selected by default in the configuration file. We need to improve this part. 

Meanwhile, could you please change back to wapiti the following models: 
 - figure
 - table
 - reference-segmenter 

and try again?  

PS: for the sake of having the comments in order I'm re-posting my answer here.

**Comment by anafandon** [comment]
@lfoppiano  Sorry I mistakenly tapped the "close with comment" .

So, I did what you said by no change, I get the same error.  I played a bit around by changing back to wapiti the 
- name: "header" 

It worked, but I'd guess that was the expected since I tried to extract the header 
` curl -v --form input=@./nogueira.pdf localhost:8080/api/processHeaderDocument`

An other interesting issue arisen is that with "processFulltextDocument" stopped working completely.

`ubuntu@stergiaras-react-dev:~/grobid_client_python/inpdfs$ curl -v --form input=@./nogueira.pdf localhost:8070/api/processFulltextDocument
*   Trying 127.0.0.1:8070...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8070 failed: Connection refused
* Failed to connect to localhost port 8070: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8070: Connection refused`

And it start working again only after I put back everything to wapiti
