### ISSUE TITLE
org.apache.naming.java.javaURLContextFactory in code example

### ISSUE THREAD

**Issue by jjbenitez26** [kermitt2/grobid#91]
I'm trying to use de GROBID JAVA API using the example in http://grobid.readthedocs.org/en/latest/Grobid-java-library/
I'm install GROBID, compile de core, and add grobid-core-0.4.0-SNAPSHOT.jar to my libraries in a NetBeans project.
My code is:
```
package grobid;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.grobid.core.*;
import org.grobid.core.data.BiblioItem;
import org.grobid.core.engines.Engine;
import org.grobid.core.factory.GrobidFactory;
import org.grobid.core.mock.MockContext;
import org.grobid.core.utilities.GrobidProperties;

/**
 *
 * @author jose
 */
public class GROBID {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        
        String pdfPath = "/home/jose/plantilla_Informatica_2015 (ok).pdf";
        String pathGHome = "/home/jose/GROBID_COMPILED/grobid-home";
        String pathGProp = "/home/jose/GROBID_COMPILED/grobid-home/config/grobid.properties";
        
        try {
            MockContext.setInitialContext(pathGHome, pathGProp);
            GrobidProperties.getInstance();
            
            Engine engine = GrobidFactory.getInstance().createEngine();
            BiblioItem bi = new BiblioItem();
            
            String doc = engine.processHeader(pdfPath, false, bi);
            System.out.println(doc);
            
        } catch (Exception ex) {
            Logger.getLogger(GROBID.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try{
                MockContext.destroyInitialContext();
            }
            catch(Exception ex){
                Logger.getLogger(GROBID.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    
}
```

When i run the proyect I get the following error:
```
GRAVE: null
javax.naming.NoInitialContextException: Cannot instantiate class: org.apache.naming.java.javaURLContextFactory [Root exception is java.lang.ClassNotFoundException: org.apache.naming.java.javaURLContextFactory]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:674)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:307)
	at javax.naming.InitialContext.init(InitialContext.java:242)
	at javax.naming.InitialContext.<init>(InitialContext.java:192)
	at org.grobid.core.mock.MockContext.setInitialContext(MockContext.java:36)
	at org.grobid.core.mock.MockContext.setInitialContext(MockContext.java:76)
	at grobid.GROBID.main(GROBID.java:33)
Caused by: java.lang.ClassNotFoundException: org.apache.naming.java.javaURLContextFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at com.sun.naming.internal.VersionHelper12.loadClass(VersionHelper12.java:72)
	at com.sun.naming.internal.VersionHelper12.loadClass(VersionHelper12.java:61)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:671)
	... 6 more
```
Any help?
Thanks in advance.

**Comment by kermitt2** [comment]
Hello !

I think the dependency to the naming package is missing in your project, e.g. in your pom.xml:

```
<dependency>
   <groupId>directory-naming</groupId>
   <artifactId>naming-java</artifactId>
   <version>0.8</version>
</dependency>
```

I have updated the dummy example project for using GROBID which shows the required dependencies: https://github.com/kermitt2/grobid-example

Hope that helps!

**Comment by jjbenitez26** [comment]
Thanks, but i have another error with the same code
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/grobid/core/mock/MockContext
	at grobid.GROBID.main(GROBID.java:33)
Caused by: java.lang.ClassNotFoundException: org.grobid.core.mock.MockContext
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 1 more
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 1.173s
Finished at: Wed Mar 09 20:21:52 CET 2016
Final Memory: 6M/81M
```
I can not download your code from my country.
any suggestions ?
Thanks in advance.

**Comment by kermitt2** [comment]
Again a problem of dependency, with the GROBID jar this time I think. Can you give your pom.xml or ant file? 

>   I can not download your code from my country.

Are you refering to the code of the example project https://github.com/kermitt2/grobid-example ? This looks strange!

**Comment by jjbenitez26** [comment]
the service is available in my country, but we have a very restricted quota system. 
My pom.xml:
<?xml version="1.0" encoding="UTF-8"?>
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>mavenGrobid</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.grobid.core</groupId>
            <artifactId>grobid</artifactId>
            <version>0.4.0-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/grobid-core-0.4.0-SNAPSHOT.jar</systemPath>
        </dependency>
        
        <dependency>
            <groupId>directory-naming</groupId>
            <artifactId>naming-java</artifactId>
            <version>0.8</version>
         </dependency>
         
    </dependencies>

</project>
```

Thanks for your time.

**Comment by jjbenitez26** [comment]
Thanks !!! You were right, dependency problem.
Thanks again !!!!

**Comment by kermitt2** [comment]
Here are the current dependencies required for using GROBID as a Java API, as present in the project grobid-example:

``` 
<dependencies>	
		<dependency>
		    <groupId>org.grobid.core</groupId>
		    <artifactId>grobid-core</artifactId>
		    <version>0.4.1-SNAPSHOT</version>
		    <scope>system</scope>
		    <systemPath>${project.basedir}/lib/grobid-core-0.4.1-SNAPSHOT.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>directory-naming</groupId>
			<artifactId>naming-java</artifactId>
			<version>0.8</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.0.1</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.0.1</version>
		</dependency>
		<dependency>
		    <groupId>com.google.guava</groupId>
		    <artifactId>guava</artifactId>
		    <version>16.0.1</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.6.6</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.6.6</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
        <dependency>
                <groupId>fr.limsi.wapiti</groupId>
                <artifactId>wapiti</artifactId>
                <version>1.5.0</version>
        </dependency>
        <dependency>
	        <groupId>com.cybozu</groupId>
		<artifactId>language-detection</artifactId>
		<version>09-13-2011</version>
	</dependency>
        <dependency>
			<groupId>net.arnx</groupId>
			<artifactId>jsonic</artifactId>
			<version>1.3.5</version>
	</dependency>
	</dependencies>
```

**Comment by jjbenitez26** [comment]
it could be this error:
```
ERROR errors.GrailsExceptionResolver  - OperationNotSupportedException occurred when processing request: [GET] /GROB/grobid
Context is read only.
```
here:
```
String pdfPath = "/home/jose/plantilla_Informatica_2015 (ok).pdf"
        String pathGHome = "/media/jose/Datos/DOCUMENTS/Datos/Gobid/GROBID_COMPILED/grobid-home"
        String pathGProp = "/media/jose/Datos/DOCUMENTS/Datos/Gobid/GROBID_COMPILED/grobid-home/config/grobid.properties"

        MockContext.setInitialContext(pathGHome, pathGProp)
        GrobidProperties.getInstance()

        Engine engine = GrobidFactory.getInstance().createEngine()
        BiblioItem bi = new BiblioItem()

        String doc = engine.processHeader(pdfPath, false, bi)
        println(doc)

        MockContext.destroyInitialContext()
```

**Comment by lfoppiano** [comment]
I'm closing this issue since the dependency problem was solved. The context issue is discussed in issue #96 .
