### ISSUE TITLE
Regarding training custom header model

### ISSUE THREAD

**Issue by Tanmay98** [kermitt2/grobid#972]
Hi @kermitt2 ,

I have been training my own header model for some time now. In the beginning when I trained on 195 files. And I recieved pretty decent rsults for mere 195 files so I increased number to 550 files and retrained my model.
To my surprise, the accuracy hasnt increased that much and the training time reduced somehow. I am pretty sure there are no errors in new xml files, since no error gets displayed while training and n_features seems to increase too proportionally when I increased number of files.

My observations looks like below for 195 training files

<img width="418" alt="Screenshot 2022-11-25 at 9 37 07 PM" src="https://user-images.githubusercontent.com/31308303/204022743-f4b957d8-099e-4ed1-afe9-b25907cc481a.png">

<img width="762" alt="Screenshot 2022-11-25 at 9 36 53 PM" src="https://user-images.githubusercontent.com/31308303/204022758-4167ca02-f2c0-4178-b057-55ee6ad02367.png">

whereas my observations on 550 training files
<img width="339" alt="Screenshot 2022-11-25 at 9 33 40 PM" src="https://user-images.githubusercontent.com/31308303/204023385-03605d87-ecbe-4e1c-8492-c6e40788ad8c.png">

<img width="764" alt="Screenshot 2022-11-25 at 9 33 06 PM" src="https://user-images.githubusercontent.com/31308303/204023399-6b7b05ae-9ad1-49ee-a28d-ee18a3d0674f.png">

What could be the possible reason for this behavior?

Thanks in advance

**Comment by kermitt2** [comment]
Hi @Tanmay98 !

> To my surprise, the accuracy hasnt increased that much and the training time reduced somehow. 

The accuracy presented by Wapiti is the accuracy on the training data, so it is not necessarily realistic wrt the actual accuracy (on new data), and not "proportional" to the actual accuracy. I think this number represents how the training data are consistent and how the "context window" of CRF is able to cover well the input training without errors. 

For getting a realistic error rate, you could use the random train-eval split or a 10-fold cross evaluation (see the [documentation](https://grobid.readthedocs.io/en/latest/Training-the-models-of-Grobid/#train-and-evaluation-separately-and-using-more-parameters-full-mode)).

Faster training time is a bit surprising I agree, but the more we have training examples with Wapiti, the better the tool can use the multi-threading training (it needs enough examples to distribute the training in the threads). It might also be a bit related to the reduced number of labels (from 50 to 40).

**Comment by majiajun0** [comment]
@Tanmay98 May I ask how you obtained so many training files? I label the data one by one, which is very slow.

**Comment by Tanmay98** [comment]
> Faster training time is a bit surprising I agree, but the more we have training examples with Wapiti, the better the tool can use the multi-threading training (it needs enough examples to distribute the training in the threads). It might also be a bit related to the reduced number of labels (from 50 to 40).

So i had increased the concurrency from 10 to 20 for faster evaluation in the grobid.yaml file. It seems that increased the training too then.
Also, the number of labels dropped from 50 to 40 is weird since the files that I added have used exactly same label tags. @kermitt2 Is there any way to print the logs of header files loaded while training. 
For example, for segmentation when I commented the lines 412-416 in build.gradle, it gave me file by file info (in case it was loaded perfectly or not like a warning log/severe log info on the terminal iteself).
I am trying to debug if the new files were loaded correctly or not by the grobid.

**Comment by Tanmay98** [comment]
> @Tanmay98 May I ask how you obtained so many training files? I label the data one by one, which is very slow.

Hi, I have my own labels for the header model, and yes I label the data one by one. And yes It is slow process :( (would probably take a week or so to generate that much number)

**Comment by kermitt2** [comment]
> Is there any way to print the logs of header files loaded while training.

I think it is working with the current version for the header files? 

I added a false tag in `007054v1.training.header.tei.xml` and I got this: 

```
716 tei files
PMC4687136.training.header.tei.xml
...
1043._KP2_Or_mmf_02_09_2009.training.header.tei.xml
007054v1.training.header.tei.xml
Warning: Unexpected starting tag toto
Exception in thread "main" org.grobid.core.exceptions.GrobidException: [GENERAL] An exception occured while running Grobid.
        at org.grobid.trainer.HeaderTrainer.addFeaturesHeaders(HeaderTrainer.java:277)
        at org.grobid.trainer.HeaderTrainer.createCRFPPData(HeaderTrainer.java:24)
        at org.grobid.trainer.AbstractTrainer.train(AbstractTrainer.java:84)
        at org.grobid.trainer.AbstractTrainer.runTraining(AbstractTrainer.java:552)
        at org.grobid.trainer.HeaderTrainer.main(HeaderTrainer.java:290)
Caused by: org.xml.sax.SAXParseException; 
systemId: file:/home/lopez/grobid/grobid-trainer/../grobid-home/../grobid-trainer/resources/dataset/header/corpus/tei/007054v1.training.header.tei.xml; 
lineNumber: 34; columnNumber: 5; The element type "toto" must be terminated by the matching end-tag "</toto>".
```

But there are conflicts with the loggers in the training tasks that I am trying to solve since a while (for all the other tasks, it's working well, so as specified in the log part of the configuration `grobid-home/config/grobid.yaml`).

**Comment by Tanmay98** [comment]
I get a warning when I add a false tag but it keeps on training (using grobid 0.7.1)

![Screenshot 2022-11-29 at 11 12 53 AM](https://user-images.githubusercontent.com/31308303/204448407-0db403b6-58ff-4b5d-bb4b-39f03a1600c8.png)

But I didnt get any warning also while loading all header files, so I am assuming all training files are loaded correctly?
Still I cannot correlate the improvement in evaluation results with the increase in number of files. 

Maybe I should try debugging manually the new training files ?
